# Generated by Django 4.1.2 on 2022-11-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
