# Generated by Django 4.1.2 on 2022-11-03 22:02

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=post.models.upload_to_file),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=post.models.upload_to_image),
        ),
    ]
