# Generated by Django 4.1.2 on 2022-11-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_documento_alter_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='documento',
        ),
    ]
